server:
  port: ${WEB_PROVIDER_DEV_PORT}

spring:
  jpa:
    database: ${JPA_DB}
    database-platform: ${DIALECT}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${PROFILE}
  application:
    name: web-provider
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    template:
      default-receive-queue: ${TEMP_DEFAULT_QUEUE}
      exchange: ${TEMP_EXCHANGE}
      routing-key: ${TEMP_ROUTING_KEY}
      vhost: ${VHOST}



